In [1]:
import numpy as np

In [2]:
lammin = 600
lammax = 900
R = 150

In [17]:
loglammin, loglammax = np.log([lammin, lammax])
dloglam = 1/R
# int(np.ceil((loglam_max - loglam_min)/dloglam))+1?
nlam = int(np.ceil((loglammax - loglammin) / dloglam) + 1)

print(nlam)


62


In [32]:
loglams = np.arange(nlam) / (nlam-1) * (loglammax - loglammin) + loglammin
loglams

array([6.39692966, 6.40357662, 6.41022359, 6.41687056, 6.42351753,
       6.4301645 , 6.43681147, 6.44345844, 6.45010541, 6.45675238,
       6.46339935, 6.47004631, 6.47669328, 6.48334025, 6.48998722,
       6.49663419, 6.50328116, 6.50992813, 6.5165751 , 6.52322207,
       6.52986903, 6.536516  , 6.54316297, 6.54980994, 6.55645691,
       6.56310388, 6.56975085, 6.57639782, 6.58304479, 6.58969176,
       6.59633872, 6.60298569, 6.60963266, 6.61627963, 6.6229266 ,
       6.62957357, 6.63622054, 6.64286751, 6.64951448, 6.65616145,
       6.66280841, 6.66945538, 6.67610235, 6.68274932, 6.68939629,
       6.69604326, 6.70269023, 6.7093372 , 6.71598417, 6.72263114,
       6.7292781 , 6.73592507, 6.74257204, 6.74921901, 6.75586598,
       6.76251295, 6.76915992, 6.77580689, 6.78245386, 6.78910083,
       6.79574779, 6.80239476])

In [33]:
np.diff(loglams)

array([0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697, 0.00664697, 0.00664697, 0.00664697, 0.00664697,
       0.00664697])

In [34]:
lams = np.exp(loglams)

In [35]:
lams[1:] / np.diff(lams)

array([150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512, 150.94506512, 150.94506512, 150.94506512,
       150.94506512])

In [36]:
lams = [lammin]
for i in range(nlam-1):
    lam = lams[i] + lams[i]/R
    lams.append(lam)
lams = np.array(lams)

In [39]:
lams

array([600.        , 604.        , 608.02666667, 612.08017778,
       616.1607123 , 620.26845038, 624.40357338, 628.56626387,
       632.75670563, 636.97508367, 641.22158422, 645.49639479,
       649.79970408, 654.13170211, 658.49258013, 662.88253066,
       667.30174753, 671.75042585, 676.22876202, 680.73695377,
       685.27520013, 689.84370146, 694.44265947, 699.0722772 ,
       703.73275905, 708.42431077, 713.14713951, 717.90145378,
       722.68746347, 727.50537989, 732.35541576, 737.2377852 ,
       742.15270376, 747.10038846, 752.08105771, 757.09493143,
       762.14223097, 767.22317918, 772.33800037, 777.48692038,
       782.67016651, 787.88796762, 793.14055407, 798.42815777,
       803.75101215, 809.10935223, 814.50341458, 819.93343734,
       825.39966026, 830.90232466, 836.44167349, 842.01795132,
       847.63140433, 853.28228035, 858.97082889, 864.69730108,
       870.46194976, 876.26502942, 882.10679628, 887.98750826,
       893.90742498, 899.86680781])

In [37]:
lams[:-1]/np.diff(lams)

array([150., 150., 150., 150., 150., 150., 150., 150., 150., 150., 150.,
       150., 150., 150., 150., 150., 150., 150., 150., 150., 150., 150.,
       150., 150., 150., 150., 150., 150., 150., 150., 150., 150., 150.,
       150., 150., 150., 150., 150., 150., 150., 150., 150., 150., 150.,
       150., 150., 150., 150., 150., 150., 150., 150., 150., 150., 150.,
       150., 150., 150., 150., 150., 150.])

In [38]:
np.diff(np.log(lams))

array([0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454, 0.00664454, 0.00664454, 0.00664454, 0.00664454,
       0.00664454])

In [44]:
1/R

0.006666666666666667